name: build-with-small-runner
on: [push, workflow_dispatch]

permissions:
  contents: read
  id-token: write

jobs:
  stress-1x4:
    runs-on: nscloud-ubuntu-22.04-amd64-1x4
    name: Stress 1x4
    env:
      IMAGE_NAME: docker-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - run: |
          sudo apt-get install -y stress-ng
          stress-ng --cpu 0 --cpu-method all -t 1h -l 100
  stress-2x4:
    runs-on: nscloud-ubuntu-22.04-amd64-2x4
    name: Stress 2x4
    env:
      IMAGE_NAME: docker-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - run: |
          sudo apt-get install -y stress-ng
          stress-ng --cpu 0 --cpu-method all -t 1h -l 100
        
