name: build-with-nsc
on: [push, workflow_dispatch]

permissions:
  contents: read
  id-token: write

jobs:
  build_with_docker:
    runs-on: nscloud
    name: Build with Docker
    env:
      IMAGE_NAME: docker-django-example
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
      VERSION: v0.0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure access to Namespace
        id: nscloud
        uses: namespacelabs/nscloud-setup@v0.0.5
        
      - name: Configure buildx
        uses: namespacelabs/nscloud-setup-buildx-action@v0.0.4

      # Run standard Docker's build-push action
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.nscloud.outputs.registry-address }}/docker-django-example:v0.0.1
