name: cache-test
on: [push, workflow_dispatch]

permissions:
  contents: read
  packages: write # This is required to push to GitHub registry

jobs:
  test-iperf3:
    runs-on: nscloud
    name: Iperf3

    steps:
      - name: Iperf3
        run: |
          sudo apt update -y 
          sudo apt install iperf3 -y
          iperf3 -c speedtest.iway.ch  -R -t 300
  
  cache-save:
    runs-on: nscloud
    name: Cache Save

    steps:
      - name: Create big file to cache
        run: |
          mkdir cache
          tail --bytes 5G /dev/urandom > cache/file.txt

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: cache
          key: ${{ runner.os }}-cache-test-${{ github.sha }}

  cache-restore:
    runs-on: nscloud
    name: Cache Restore
    needs: cache-save

    steps:      
      - uses: actions/cache/restore@v3
        with:
          path: cache
          key: ${{ runner.os }}-cache-test-${{ github.sha }}
