name: cache-test
on: [push, workflow_dispatch]

permissions:
  contents: read
  packages: write # This is required to push to GitHub registry

jobs:
  cache-save:
    runs-on: nscloud
    name: Cache Save

    steps:
      - name: Create big file to cache
        run: |
          tail --bytes 5G /dev/urandom > to_cache.txt

      - uses: actions/cache/save@v3
        id: save
        if: always()
        with:
          path: to_cache.txt
          key: ${{ runner.os }}-cache-test-${{ hashFiles('to_cache.txt') }}

  cache-restore:
    runs-on: nscloud
    name: Cache Restore
    needs: cache-save

    steps:      
      - uses: actions/cache/restore@v3
        id: restore
        with:
          path: from_cache.txt
          key: ${{ runner.os }}-cache-test-
          restore-keys: ${{ runner.os }}-cache-test-
